- id: '1673351269459'
  alias: Encender Cine
  description: Enciende la tele y todas las luces
  trigger:
  - platform: device
    device_id: d9192629be7456ee8c341b137d2eac5a
    domain: media_player
    entity_id: media_player.television
    type: turned_on
  condition: []
  action:
  - if:
    - condition: sun
      before: sunrise
      after: sunset
    then:
    - type: turn_on
      device_id: 247c74391203fa852830509086051beb
      entity_id: light.bombilla_salon
      domain: light
    - type: turn_on
      device_id: 848c02320a43459fe3f4a094803baffb
      entity_id: light.luz_tele
      domain: light
      brightness_pct: 100
  - service: remote.send_command
    data:
      command: power_on
      device: amplificador
      num_repeats: 2
      delay_secs: 1
    target:
      entity_id: remote.broadlink_remote_hub
  - service: remote.send_command
    data:
      command: CD-R
      device: amplificador
      delay_secs: 2
      num_repeats: 2
    target:
      entity_id: remote.broadlink_remote_hub
  mode: single
- id: '1673351355869'
  alias: Apagar Cine
  description: Apaga la tele y todas las luces del salón
  trigger:
  - platform: device
    device_id: d9192629be7456ee8c341b137d2eac5a
    domain: media_player
    entity_id: media_player.television
    type: turned_off
  condition: []
  action:
  - type: turn_off
    device_id: 247c74391203fa852830509086051beb
    entity_id: light.bombilla_salon
    domain: light
  - type: turn_off
    device_id: 848c02320a43459fe3f4a094803baffb
    entity_id: light.luz_tele
    domain: light
  - service: remote.send_command
    data:
      command: power_off
      device: amplificador
    target:
      entity_id: remote.broadlink_remote_hub
  mode: single
- id: '1673456675256'
  alias: Aspirar cocina
  description: Aspira el area de la cocina
  trigger: []
  condition: []
  action:
  - service: xiaomi_miio.vacuum_clean_zone
    data:
      repeats: 2
      zone:
      - - 20666
        - 20734
        - 23666
        - 26084
    target:
      entity_id: vacuum.aspirador
  mode: single
- id: '1673517960702'
  alias: Auto - Encender Cine
  description: Si está la tele encendida cuando se va el sol, enciende las luces de
    la tele.
  trigger:
  - platform: sun
    event: sunset
    offset: 0
  condition:
  - condition: device
    device_id: d9192629be7456ee8c341b137d2eac5a
    domain: media_player
    entity_id: media_player.television
    type: is_on
  action:
  - type: turn_on
    device_id: 848c02320a43459fe3f4a094803baffb
    entity_id: light.luz_tele
    domain: light
  - type: turn_on
    device_id: 247c74391203fa852830509086051beb
    entity_id: light.bombilla_salon
    domain: light
  mode: single
- id: '1674297151052'
  alias: Escritorio pekes
  description: ''
  trigger:
  - type: turned_on
    platform: device
    device_id: 0976c25dfffbf93553597e13be940ebb
    entity_id: binary_sensor.boton_pekes
    domain: binary_sensor
  condition: []
  action:
  - type: toggle
    device_id: 31c92efdcfabc776b8f6daf25a4e7553
    entity_id: switch.enchufe_pekes_outlet
    domain: switch
  mode: single
- id: '1675873146590'
  alias: tv_on_lights
  description: tv_on_lights
  trigger: []
  condition: []
  action:
  - type: turn_on
    device_id: 848c02320a43459fe3f4a094803baffb
    entity_id: light.luz_tele
    domain: light
  - type: turn_on
    device_id: 247c74391203fa852830509086051beb
    entity_id: light.bombilla_salon
    domain: light
    flash: long
  mode: single
- id: '1675873191214'
  alias: tv_off_lights
  description: tv_off_lights
  trigger: []
  condition: []
  action:
  - type: turn_off
    device_id: 848c02320a43459fe3f4a094803baffb
    entity_id: light.luz_tele
    domain: light
  - type: turn_off
    device_id: 247c74391203fa852830509086051beb
    entity_id: light.bombilla_salon
    domain: light
  mode: single
