
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

vacuum:
  - platform: xiaomi_miio
    host: !secret xiaomi_vacuum_ip
    token: !secret xiaomi_vacuum_token

camera:
  - platform: xiaomi_cloud_map_extractor
    host: !secret xiaomi_vacuum_ip
    token: !secret xiaomi_vacuum_token
    username: !secret xiaomi_user
    password: !secret xiaomi_password
    draw: ['all']
    attributes:
      - calibration_points

sensor:
  - platform: systemmonitor
    resources:
      - type: disk_use_percent
      - type: memory_use_percent
      - type: load_1m

device_tracker:
  - platform: arpscan_tracker
    interval_seconds: 15
    consider_home: 120
    include:
      - 192.168.1.108
      - 192.168.1.109
      - 192.168.1.175

logger:
  default: info
  logs:
    custom_components.arpscan_tracker: debug
