
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

#input_boolean: !include input_booleans.yaml
#binary_sensor: !include binary_sensors.yaml
#sensor: !include sensors.yaml

vacuum:
  - platform: xiaomi_miio
    host: !secret xiaomi_vacuum_ip
    token: !secret xiaomi_vacuum_token

camera:
  - platform: xiaomi_cloud_map_extractor
    host: !secret xiaomi_vacuum_ip
    token: !secret xiaomi_vacuum_token
    username: !secret xiaomi_user
    password: !secret xiaomi_password
    draw: ['all']
    attributes:
      - calibration_points

sensor:
  - platform: systemmonitor
    resources:
      - type: disk_use_percent
      - type: memory_use_percent
      - type: load_1m
  - platform: time_date
    display_options:
      - 'time'
      - 'date'
      - 'date_time'
      - 'date_time_utc'
      - 'date_time_iso'
      - 'time_date'
      - 'time_utc'
      - 'beat'

device_tracker:
  - platform: arpscan_tracker
    interval_seconds: 15
    consider_home: 120
    include:
      - 192.168.1.108
      - 192.168.1.109

logger:
  default: info
  logs:
    custom_components.arpscan_tracker: debug
    
template:
  - binary_sensor:
    - name: People home
      state: >
        {{ is_state('person.samuelmp', 'home')
        or is_state('person.paloma', 'home') }}
      device_class: "presence"
      icon: >
        {% if is_state('person.samuelmp', 'home') or is_state('person.paloma', 'home')  %}
          mdi:home-assistant
        {% else %}
          mdi:home-off
        {% endif %}
  
