# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  extra_module_url:
    - /hacsfiles/lovelace-card-mod/card-mod.js
  themes: !include_dir_merge_named themes

# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
#input_boolean: !include input_booleans.yaml
#binary_sensor: !include binary_sensors.yaml
sensor: !include includes/sensors.yaml

vacuum:
  - platform: xiaomi_miio
    host: !secret xiaomi_vacuum_ip
    token: !secret xiaomi_vacuum_token

camera:
  - platform: xiaomi_cloud_map_extractor
    host: !secret xiaomi_vacuum_ip
    token: !secret xiaomi_vacuum_token
    username: !secret xiaomi_user
    password: !secret xiaomi_password
    name: vacuum_map
    colors:
      color_robo: [224, 224, 224]
      color_charger: [27, 117, 27]
      color_path: [30, 80, 113]
      color_goto_path: [30, 80, 113]
      color_map_wall_v2: [30, 30, 30]
      color_obstacle: [30, 30, 30]
      color_virtual_walls: [255, 0, 0, 60]
      color_no_go_zones_outline: [255, 0, 0, 60]
      color_no_go_zones: [255, 0, 0, 28]
      color_scan: [0, 0, 0, 0]
      color_map_inside: [0, 0, 0, 0]
      color_map_outside: [0, 0, 0, 0]
      color_grey_wall: [0, 0, 0, 0]
      color_map_wall: [0, 0, 0, 0]
      color_zones_outline: [0, 0, 0, 0]
      color_zones: [0, 0, 0, 0]
    room_colors:
      1: [42, 46, 48]
      2: [42, 46, 48]
      16: [42, 46, 48]
      17: [42, 46, 48]
      18: [42, 46, 48]
    draw:
      - all
    map_transformation:
      scale: 2
      trim:
        top: 19
        right: 21
        bottom: 24
        left: 21
    sizes:
      charger_radius: 10
      vacuum_radius: 10
    attributes:
      - calibration_points
    scan_interval: 10

input_boolean:
  thermostat_dropdown:
    name: Thermostat Dropdown State
    icon: mdi:chevron-down

device_tracker:
  - platform: arpscan_tracker
    interval_seconds: 15
    consider_home: 120
    include:
      - 192.168.1.108
      - 192.168.1.109

binary_sensor:
  - platform: tod
    name: Night
    after: sunset
    before: sunrise

  - platform: tod
    name: Day
    after: sunrise
    before: sunset

spotcast:
  sp_dc: !secret sp_dc
  sp_key: !secret sp_key
  country: ES #optional, added in 3.6.24

input_text:
  room_cleaning:
    name: Currently Cleaning Room
    initial: charging

# sensor:
# - platform: systemmonitor
#   resources:
#     - type: disk_use_percent
#       arg: /
#     - type: memory_use_percent
#     - type: processor_use
#     - type: last_boot
#   scan_interval: 120
# - platform: template
#   sensors:
#     nightstate_100:
#       friendly_name: Night State
#       value_template: "{% if is_state('sun.sun', 'below_horizon') %}100{% else %}0{% endif %}"
#     daystate_100:
#       friendly_name: Day State
#       value_template: "{% if is_state('sun.sun', 'below_horizon') %}0{% else %}100{% endif %}"

# sensor:
#   – platform: template
#     sensors:
#       nightstate:
#         friendly_name: Night State
#         value_template: "{% if is_state('sun.sun', 'below_horizon') %}1{% else %}0{% endif %}"

logger:
  default: info
  logs:
    custom_components.arpscan_tracker: debug

# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
## Templates >>> sensors > binary_sensors > triggers
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
template: !include_dir_merge_list includes/templates/

lovelace:
  mode: yaml
  dashboards:
    lovelace-full:
      mode: yaml
      filename: ui-lovelace_full.yaml
      title: Full Tablet
      icon: mdi:cellphone
      show_in_sidebar: true
    lovelace-milhouse:
      mode: yaml
      filename: ui-lovelace-milhouse.yaml
      title: Milhouse
      icon: mdi:home-assistant
      show_in_sidebar: true
  resources: [
      { url: /hacsfiles/apexcharts-card/apexcharts-card.js, type: module },
      { url: /hacsfiles/bar-card/bar-card.js, type: module },
      { url: /hacsfiles/button-card/button-card.js, type: module },
      { url: /hacsfiles/custom-icons/custom-icons.js, type: module },
      { url: /hacsfiles/lovelace-layout-card/layout-card.js, type: module },
      {
        url: /hacsfiles/lovelace-more-info-card/more-info-card.js,
        type: module,
      },
      { url: /hacsfiles/lovelace-mushroom/mushroom.js, type: module },
      {
        url: /hacsfiles/lovelace-slider-entity-row/slider-entity-row.js,
        type: module,
      },
      {
        url: /hacsfiles/lovelace-xiaomi-vacuum-map-card/xiaomi-vacuum-map-card.js,
        type: module,
      },
      { url: /hacsfiles/swipe-card/swipe-card.js, type: module },
      { url: /hacsfiles/tabbed-card/tabbed-card.js, type: module },
      { url: /hacsfiles/stack-in-card/stack-in-card.js, type: module },
      {
        url: /hacsfiles/mini-media-player/mini-media-player-bundle.js,
        type: module,
      },
      { url: /hacsfiles/simple-thermostat/simple-thermostat.js, type: module },
      {
        url: /hacsfiles/config-template-card/config-template-card.js,
        type: module,
      },
      {
        url: /hacsfiles/mini-graph-card/mini-graph-card-bundle.js,
        type: module,
      },
      {
        url: /hacsfiles/simple-weather-card/simple-weather-card-bundle.js,
        type: module,
      },
      { url: /hacsfiles/spotify-card/spotify-card.js, type: module },
      { url: /hacsfiles/weather-card/weather-card.js, type: module },
      { url: /hacsfiles/lovelace-hui-element/hui-element.js, type: module },
      { url: /hacsfiles/light-popup-card/light-popup-card.js, type: module },
      { url: /hacsfiles/kiosk-mode/kiosk-mode.js, type: module },
      { url: /hacsfiles/lovelace-thermostat-card/main.js, type: module },

      { url: "/local/marked.min.js?v=4.2.5", type: module },
      { url: "/local/vanilla-tilt.min.js?v=1.8.0", type: module },
      { url: "/local/browser_mod_icon.js?v=0.5", type: module },
      { url: "/local/decluttering-card.js", type: module },
      { url: "/local/collapsable-cards.js", type: module },
      #{ url: '/local/bar-card.js',                                                  type: module },
      #{ url: '/local/more-info-card.js',                                            type: module },
      { url: "/local/digital-clock.js", type: module },
      { url: "/local/hourly-weather/hourly-weather.js", type: module },

      { url: "/local/js/buien-rain-card.js?v=0.0.60", type: module },
      { url: "/local/js/light-slider-card-lajv.js", type: module },
      { url: "/local/js/nightscout-card.js?v=0.0.31", type: module },

      { url: "/local/fonts.css?v=2.1", type: css },
    ]
